[package]
name = "tuicol"
version = "0.1.0"
edition = "2024"

[dependencies]
glicol = "0.13.5"
glicol_synth = "0.13.5"
ratatui = "0.29.0"
tui-textarea = "0.7.0"
crossterm = "0.28"
rodio = "0.20.1"
cpal = "0.15.3"
anyhow = "1.0.97"

[features]
default = ["jack"]
jack = ["cpal/jack"]
